# escape=\

FROM ubuntu:20.04 as nvm-builder
LABEL maintainer="Jeremi Rynkiewicz JRPC <jeremi@jrpc.pl>"
LABEL name="nvm-builder-ubuntu"
LABEL version="0.1.0"

# Declare constants
ENV NVM_DIR         /usr/local/nvm
ENV NVM_VERSION     v0.39.2
ENV NODE_VERSION    v10.24.1
ENV NODE_PATH       $NVM_DIR/$NODE_VERSION/lib/node_modules
ENV PATH            $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install pre-reqs
RUN apt-get update
RUN apt-get -y install curl build-essential git vim python3 python libusb-1.0-0-dev

# Pre-create NVM dir
RUN mkdir /usr/local/nvm

# Install NVM
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash

# Install NODE
RUN source $NVM_DIR/nvm.sh; \
    nvm install $NODE_VERSION; \
    nvm use --delete-prefix $NODE_VERSION;

# Enter into working directory
WORKDIR /usr/app

# Download app sources
RUN git clone -b master --single-branch https://github.com/jrynkiew/iotex-desktop-wallet.git /usr/app; \
    npm install; \
    npm run build;
        
# Enter into the work directory to build application
WORKDIR /usr/app/src/electron
